export const data = [
  "狂上加狂异香",
  "东方有鱼他的冲喜小娘",
  "九月流火宫斗不如当太",
  "木沐梓诸事皆宜百无禁",
  "二恰替姐姐嫁给病娇",
  "老草吃嫩十贯娘子",
  "小舟遥遥偏执太子白月",
  "维和粽子一朵花开百花",
  "Racing car sprays burning fuel into crowd.",
  "Japanese princess to wed commoner.",
  "Australian walks 100km after outback crash.",
  "Man charged over missing wedding girl.",
  "Los Angeles battles huge wildfires.",
  "Racing car sprays burning fuel into crowd.",
  "Japanese princess to wed commoner.",
  "Australian walks 100km after outback crash.",
  "Man charged over missing wedding girl.",
  "Los Angeles battles huge wildfires.",
  "Racing car sprays burning fuel into crowd.",
  "Japanese princess to wed commoner.",
];
